### ISSUE TITLE
Improve Anchor Tag Display Names

### ISSUE THREAD

**Issue by ghost** [BoiseStateCS401/CS401-activity-justjames#3]
The display names for your anchor tags for html and css resources are currently the url of the resource themselves.  I would suggest changing the display name to something cleaner and descriptive.  For example: _Mozilla Developer - HTML_ or _Wiki - CSS_.

Everything else on the site looks great and all requirements are met.  Great job!

**Comment by jamesnorwood** [comment]
Thanks for the feedback @pcullings. Display names have been updated.
