### ISSUE TITLE
Pre tag could be used more efficiently

### ISSUE THREAD

**Issue by marissaschmidt** [BoiseStateCS401/CS401-activity-justjames#4]
https://github.com/BoiseStateCS401/CS401-activity-justjames/blob/832ec930a7980f8f9a874198fb990fb083d183a7/index.html#L86

The pre tag preserves whitespace so you don't have to use <br> tags for every new line. E.g.

```
<pre>
public class HelloWorld
{
    public static void main(String[] args)
    {
    }
}
</pre>
```

**Comment by jamesnorwood** [comment]
Thanks @marissaschmidt . <pre> tags have been updated.
